# Generated by Django 4.0.5 on 2022-07-15 12:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TypesInPhone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('types', models.CharField(max_length=50, verbose_name='Типы номеров')),
            ],
            options={
                'verbose_name': 'Тип номера',
                'verbose_name_plural': 'Типы номеров',
            },
        ),
        migrations.CreateModel(
            name='ContactInPhone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('surname', models.CharField(max_length=50, verbose_name='Фамилия')),
                ('name', models.CharField(max_length=50, verbose_name='Имя')),
                ('patronymic', models.CharField(max_length=50, verbose_name='Отчество')),
                ('numbers', models.PositiveBigIntegerField(verbose_name='номер')),
                ('types_in_phone', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='testtelebook.typesinphone', verbose_name='Тип номера')),
            ],
            options={
                'verbose_name': 'Имя в телефонной книге',
                'verbose_name_plural': 'Имена в телефонной книге',
            },
        ),
    ]
