# Generated by Django 4.0.5 on 2022-07-11 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testtelebook', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='typesinphone',
            name='numbers',
            field=models.PositiveBigIntegerField(default=1, verbose_name='номер'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='typesinphone',
            name='types',
            field=models.PositiveBigIntegerField(choices=[(None, 'Выбрать тип'), (1, 'Мобильный'), (2, 'Домашний'),
                                                          (3, 'Рабочий'), (4, 'Личный'), (5, 'почта')],
                                                 default=1, verbose_name='Тип номера'),
        ),
    ]
