# Generated by Django 4.0.5 on 2022-07-11 14:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('testtelebook', '0002_typesinphone_numbers_alter_typesinphone_types'),
    ]

    operations = [
        migrations.AlterField(
            model_name='typesinphone',
            name='contact',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='testtelebook.contactinphone', verbose_name='Полное имя'),
        ),
    ]
